### ISSUE TITLE
Function naming

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#127]
I noticed that we refer to unifrac with UniFrac (e.g. in `calculateUniFrac`).

The original authors and QIIME2 seem to use name "Unifrac" with no uppercase F. 

Perhaps a minor detail but I would prefer changing this to the standard spelling. 

If @FelixErnst agrees, @shigdel could make a PR on this.

**Comment by FelixErnst** [comment]
I used the CamelCase because of phyloseq implementation.

You can change it of course. Is it worth having two function names?

**Comment by antagomir** [comment]
One option is to have an alias and use the standard version in OMA and other sources. But I am not sure if this causes more confusion than helps.

**Comment by TuomasBorman** [comment]
Hi @shigdel ! Thanks for your contribution.

It looks like you accidentally made a commit directly to `microbiome/mia` master and not your own forked project `shigdel/mia`. 
I reverted the commit, because it did not passed tests. That was because you changed the name of the function, but there are still some files where the function is called with its old name. 
 
In order to pass those tests, you have to change the name from all the files. In RStudio, you can find all instances from all files with `shift+ctrl+f`

![image](https://user-images.githubusercontent.com/60338854/129488827-e7f14755-62cb-4304-8373-cc36ad77c2b7.png)

Smooth workflow goes like this

1. Make changes to your forked project. 
- Change all the instances. 
- `calculateUniFrac.Rd` file (manual files) are rendered based on `calculateUniFrac.R` file. To create new Rd file, run `devtools::document()`

2. Create a pull request 
- link this issue to the PR
- In PR, we can discuss if there is some things that could be done better 
- Tests are ran automatically to PRs. This way it is possible to see if tests are passed without committing directly into the master (you can run also local tests with `devtools::check()` )
- After approvements, we can merge PR into the master

Please ask if something is unclear

-Tuomas

**Comment by antagomir** [comment]
Thanks both.

@shigdel you can make the PR by forking the repository as Tuomas explained, making your changes, then opening a PR against microbiome/mia master branch. If it is unclear how to do any of this, ask us online. 

Another option would be that you clone microbiome/mia directly (if you have this already), create a new *branch*, and make PR from that branch to master. But this requires that you writing access, which I have now removed so that you can safely play around and we can accept the PR when it is ready for merging. 

I have now limited writing permissions so that only miaverse-developers team (and Admins) has full writing/push permissions. The project is growing and we need to start managing permissions more carefully.

**Comment by FelixErnst** [comment]
Any news on this?

**Comment by antagomir** [comment]
This is ready to be merged I think?

**Comment by TuomasBorman** [comment]
Yes, I think it's ready
