### ISSUE TITLE
ape dependency causing intermitant test errors

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/mia#162]
https://master.bioconductor.org/checkResults/3.14/bioc-LATEST/mia/nebbiolo2-checksrc.html

**Comment by TuomasBorman** [comment]
Hi,

I have been trying to solve this. 

The email was forwarded to me, and I agree that `ape::all.equal.phylo` cause this. I have been trying to find, what are the situations where this happens. 

1. I have been running the tests ( `devtools::test()` ), and I have been able to reproduce the error locally. It does not happen all the time, but maybe every second time. 

2. I have been running `ape::all.equal.phylo( rowTree(tse), rowTree(tse) )` in different situations, but I have not been able to reproduce the error by running the function itself.

I think that it is quite hard to get rid off the whole `ape` dependency. I can report this to them, but without reproducible example, because I have not been able to create one. Then let's see what they can do about it.

Because it seems that the error only occurs when tests are run and only with one function, I think that this might not cause any further problems for us. 

**This error occurs when**

test-4IO.R --> e.g., line 372 --> `expect_equal( phyloseq::phy_tree(phy), rowTree(tse) )` --> calls `all.equal()` --> calls `all.equal.phylo()` --> internal function `same.node()` is called inside `for-for-loop`. 

I'm not sure if that [quite intensive double for-loop](https://rdrr.io/cran/ape/src/R/all.equal.phylo.R) cause problems, because some times phylo trees are quite big.

Temporary fix for our problem could be that we change the test little bit. --> `expect_identical( phyloseq::phy_tree(phy), rowTree(tse) )` 

After this change, test did not cause any errors even though I ran it multiple times locally.

-Tuomas

**Comment by FelixErnst** [comment]
Can you remove the test or maybe rework it? I have the suspision that testthat is messing with some environments and is confounding the issue.

**Comment by TuomasBorman** [comment]
I can remove tests
`expect_equal( phyloseq::phy_tree(phy), rowTree(tse) )`
or I can modify them to be
`expect_identical( phyloseq::phy_tree(phy), rowTree(tse) )` which did not have the same issue, at least when I ran test locally

This identical is doing the same thing but it is little it stricter

Should I just push these changes directly to master?

**Comment by TuomasBorman** [comment]
Reopened the issue because it is unsure if the fix works

**Comment by FelixErnst** [comment]
Its pushed to Bioc. Let's see

**Comment by TuomasBorman** [comment]
Now Linux and Windows are OK, but MacOS has problem

When running tests and calling 

`40: getPrevalentTaxa(GlobalPatterns, detection = 0.004, prevalence = 0.1,     as_relative = TRUE, rank = "Family")`
-->
`36: do.call(agglomerateByRank, args)`

there is `*** recursive gc invocation` which leads to  `*** caught segfault ***`

**Comment by FelixErnst** [comment]
I don't see that anymore. I am closing this, but lets keep an eye on it.
