### ISSUE TITLE
Error when trying to agglomerate by taxonomic level (altExp function)

### ISSUE THREAD

**Issue by asierFernandezP** [microbiome/mia#168]
Hi,

When trying to agglomerate the Summarized Experiment data by taxonomic level (e.g. Phylum) as explained in the tutorial, I get the error below:

My code:

```
se <- SummarizedExperiment(assays = list(counts = counts),
                                     rowData = tax,
                                     colData = samples)

altExp(se,"Phylum") <- agglomerateByRank(se, "Phylum")
```

The error I get:

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘altExp<-’ for signature ‘"SummarizedExperiment", "character"’
```

----

The SE is correctly built as I can work with other functions in the package without any problems. I can also agglomerate by taxonomic level using the rank argument to perform the agglomeration on the fly and it works fine to get the prevalence. The problem seems to be only with "altExp". I don't know if it is possible to plot the prevalence using only the agglomeration on the fly.

----

Thank you,

Asier

**Comment by TuomasBorman** [comment]
Hi Asier!

Thanks for this issue. We are trying to make these tutorials as simple as possible, and that part is actually misleading. 

`SummarizedExperiment` objects do not include `altExp` slot. However, `TreeSummarizedExperiment` objects have. You can easily convert `SE` into `TreeSE`.

That object in tutorials is actually `TreeSE` even though object's name is `se`. I think we should change that to be more consistent, because we are already using object names `se` and `tse`. 

```
# There is no altExp slot
se
# Convert SE into TreeSE
se <- as(se, "TreeSummarizedExperiment")
# There is a altExp slot
se
# Now it works
se_phylum <- agglomerateByRank(se, "Phylum")
altExp(se,"Phylum")  <- se_phylum
```

> I don't know if it is possible to plot the prevalence using only the agglomeration on the fly.

You can plot prevalence also by just using the `SE` itself. `altExp(se,"Phylum")` just retrieves `se_phylum` object from `altExp` slot of `se`.

`plotRowData(se_phylum, "prevalence", colour_by = "Phylum")`
 and 
`plotRowData(altExp(se,"Phylum"), "prevalence", colour_by = "Phylum")`
are the same.


-Tuomas

**Comment by antagomir** [comment]
Yes, notation should be harmonized. `se` for `SE` and `tse` for `TreeSE`
