### ISSUE TITLE
agglomerateByRank(agglomerateTree = TRUE) fails with highest rank

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#174]
Hi,

using `rank="Kingdom"` or `rank="Domain"` breaks `agglomerateByRank()` when using `agglomerateTree = TRUE`:

```r
data(GlobalPatterns)
agglomerateByRank(GlobalPatterns, rank = "Kingdom", agglomerateTree = TRUE)
# Error: rownames of 'x' mismatch with node labels of the tree 
#  Try 'changeTree' with 'rowNodeLab' provided.
# In addition: Warning message:
# In toTree(td) : The root is added with label 'ALL'
agglomerateByRank(GlobalPatterns, rank = "Phylum", agglomerateTree = TRUE) # this works
```

Best,
Bela

**Comment by TuomasBorman** [comment]
Hi,

thanks! 

It seems that there is a small error when that new tree is built. 

Information for building that tree is fetched from `rowData(x)`. When there is only one taxonomic level left (Kingdom), the data is subsetted so that it includes only one column 

--> it is a vector, and now it does not include name of taxonomic level. --> tree tips are named incorrectly --> they do not match with `rownames`

-Tuomas
