### ISSUE TITLE
Conversions data formats from phyloseq to TSE

### ISSUE THREAD

**Issue by taekwonleo-yuhao** [microbiome/mia#200]
Dear developers,
I am learning how to use mia to analyze microbiome data. But mia needs to convert the phyloseq format into TreeSummarizedExperiment format.
I try to use the function makeTreeSummarizedExperimentFromPhyloseq from mia. But it gives me an error message.
library("mia"); packageVersion("mia")
#[1] ‘1.3.9’

ps1_ABX
#phyloseq-class experiment-level object
#otu_table() OTU Table: [ 788 taxa and 1077 samples ]
#sample_data() Sample Data: [ 1077 samples by 13 sample variables ]
#tax_table() Taxonomy Table: [ 788 taxa by 7 taxonomic ranks ]
#phy_tree() Phylogenetic Tree: [ 788 tips and 786 internal nodes ]

convert phyloseq to TSE
GlobalPatterns_ABX_TSE <- makeTreeSummarizedExperimentFromPhyloseq(ps1_ABX)

Error in validObject(.Object) :
invalid class “SummarizedExperiment” object:
‘x@assays’ is not parallel to ‘x’
10. stop(msg, “: “, errors, domain = NA)
9. validObject(.Object)
8. initialize(value, ...)
7.i nitialize(value, ...)
6. new(“SummarizedExperiment”, NAMES = names, elementMetadata = rowData,
colData = colData, assays = assays, metadata = as.list(metadata))
5. new_SummarizedExperiment(assays, ans_rownames, rowData, colData,
metadata)
4. SummarizedExperiment(...)
3. SingleCellExperiment(...)
2. TreeSummarizedExperiment(assays = assays, rowData = rowData,
colData = colData, rowTree = rowTree, referenceSeq = referenceSeq)

I tried to convert with another phyloseq file on my hand and get the same error. But I successfully converted the phyloseq object from mia tutorials. Could you please tell me how to fix this issue?

And this is my phyloseq object in RData file [https://www.dropbox.com/s/mn0vv670zccaswk/ps1_ABX_errorinmia.RData?dl=0](url)

Thanks,
Yuhao

**Comment by TuomasBorman** [comment]
Hi Yuhao!

Thanks for this issue, this helps us a lot. 

`(Tree)SummarizedExperiment` requires that samples and features match in specific way
- samples 
   - `colnames of assay` and `rownames of sample meta data` should match
- features
   - `rownames of assay` and `rownames of taxonomy data` should match

In your case, they do not match because **your `assay` has samples in rows and taxa in columns**. 

As a quick fix, you can transpose your `assay`
```
otu_table(ps1_ABX) <- t(otu_table(ps1_ABX))
GlobalPatterns_ABX_TSE <- makeTreeSummarizedExperimentFromPhyloseq(ps1_ABX)
```

Then it should work.


I found out that this is a feature for `phyloseq` object; orientation of `assay` can vary. There is a slot that tells the orientation. 
```
ps1_ABX@otu_table@taxa_are_rows
FALSE
```
Currently, the function does not take this into account.  I will fix it.

-Tuomas
