### ISSUE TITLE
agglomerateByRank to drop the 

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#210]
Agglomeration from Species to Genus level (and other analogous things) still keeps the Species in rowData, although they become obsolete in the agglomeration. Could we drop the taxonomy ranks by default, or at least provide an option to do so?

```
data(GlobalPatterns)
rowData(agglomerateByRank(GlobalPatterns, "Genus"))
```

**Comment by TuomasBorman** [comment]
You mean that when agglomeration is done at `"Phylum"` level, columns `"Class", "Order", ... "Species"` are removed so that rowData includes only columns `"Kingdom"` and `"Phylum"`? 

I think that could be justified. I think I could create a hidden option (`...`) for that. Let's see if we decide to do something else when the functionality is available

-Tuomas
