### ISSUE TITLE
estimateDiversity naming scheme

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#24]
The function name `estimateDiversity` is somewhat confusing since we have the concepts of alpha, beta, and gamma diversity in (microbial) ecology. Hence, `estimateAlphaDiversity` would be a more descriptive name.

**Comment by FelixErnst** [comment]
I don't like the term beta diversity since it is nothing more than a distance measurements. In most of the microbiome related packages this is not made clear, which is a major pain in the ***, sorry for the language.  It confuses users by creating a isolation layer between, what, how and why someone wants to calcultate a beta diversity.

Regarding the the gamma diversity, I haven't made up my mind. Since it takes into account alpha and beta, I am not sure how to implement it in the `SE` context.

For now, I would like to explain the specifics in the book and educate the user that way. calculateDistance is available for that reason and the MDS based on the distance is something which needs to be explained to the user in detail. The man oage of the functions are also a great place to add the information in regards to microbiome analysis. aliases are also part of this.

**Comment by antagomir** [comment]
No objections in general. The terminology is firmly established in ecological literature, and it is a decision to make, anyway, whether we want to comply with some of the standard terminology (e,g, beta diversity), or stick to their more generic equivalents (e.g. distance or dissimilarity). In fact beta diversity as a concept covers both distances and dissimilarities.. for clarity it is not necessarily a bad thing to have some support for this; aliases might be a good light-weight solution for that.

Anyway, regardless of what we think about beta diversity as a term, the function name `estimateDiversity` is not clear about the type of diversity it refers to. Even if we would like to abandon the use of "beta diversity", we may still like to use `estimateAlphaDiversity` here, for the sake of clarity.

**Comment by FelixErnst** [comment]
So lets go for wrapper now. 

How do you think about the different terms `estimate` and `calculate`? The distinction I think is quite important for me, but can we really see this as distinct for alpha and beta diversity?

**Comment by antagomir** [comment]
How do you define the distinction? These seem somewhat overlapping to me. I agree that clarity is good.

Is `estimateAlphaDiversity` going the be the wrapper name?

**Comment by FelixErnst** [comment]
Yes for `estimateAlphaDiversity`. I will add it since I want to rework the `breakaway` dependency.

estimation I regard something with any error on it, whereas calculation is something more fixed.

**Comment by FelixErnst** [comment]
fixed with 0ed6a22
