### ISSUE TITLE
rowTree can store multiple trees, this is not taken into account currently

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#286]
`rowTree` and `colTree` slots can store multiple trees. Our methods do not take this into account. For example, `estimateFaith` takes just the first tree. 

I suggest to add `whichTree` argument. This takes character values that specify the `rowTree`. 

`tree <- rowTree(tse, "phylo")`

After that, the `tse` is subsetted based on `rowTree`. (Take only those rows that are present in tree.) The faith index is calculated based on subsetted data. 

Also other functions should be checked. Probably we can have similar functionality in those

**Comment by antagomir** [comment]
Very good point and agreed that other functions could be checked as well. If they cannot all be solved now, at least an issue could be opened.

If there are multiple trees perhaps it is better to require that the user explicitly specifies the tree, otherwise throwing an error. The error message could list the available tree names. The manpage should have a brief explanation.

**Comment by antagomir** [comment]
Faith is written with capital as it comes from person name..

**Comment by TuomasBorman** [comment]
Check

- estimateDiversity
- calculateDPCoA (line 148)
- calculateUnifrac (line 144)
- mergeRows (line 304)
