### ISSUE TITLE
tse imported from phyloseq subset by colData fails

### ISSUE THREAD

**Issue by aatsinki** [microbiome/mia#287]
Hi! I have mia_1.4.0 in use, and I struggled to subset the tse object that was imported from phyloseq. It was remedied by loading the data with TreeSummarizedExperiment:

```
pseq <- readRDS("./data/processed/phylosed_longitudinal_21072021.rds")

tse <- makeTreeSummarizedExperimentFromPhyloseq(pseq) 
tse <- tse[, tse$timepoint %in% c("14","30")]
```

I get error:
Error in proxy[, ..., drop = FALSE] : incorrect number of dimensions

However, everything goes smoothly with the following:

```
counts <- t(otu_table(pseq))
counts <- as.matrix(counts)
assays <- SimpleList(counts = counts)

d <- read_tsv("./data/processed/cleaned_metadata_sequenced_samples_21072022.txt")
samdf <- DataFrame(d)
taxa <- DataFrame(tax_table(pseq))

# Create TreeSE
tse <- TreeSummarizedExperiment(assays = assays,
                                colData = samdf,
                                rowData = taxa
)

tse <- tse[, tse$timepoint %in% c("14","30")]

````
I don't know if anyone else has bumped in to this error before.

**Comment by TuomasBorman** [comment]
Hi!

Thanks for this issue. This error should be fixed in the development branch. 

Bioc-devel branch will be updated in couple of days. If you want to use the latest version before that, load the package directly from the Github, for example like this `devtools::install_github("microbiome/mia")`

Please inform us, if the function is still not working correctly after updating it to the latest version

-Tuomas
