### ISSUE TITLE
UniFrac 

### ISSUE THREAD

**Issue by microsud** [microbiome/mia#336]
Currently the UniFrac distance calculation is ported from phyloseq to work with TreeSummarizedExperiment objects. I recently came across this issue in phyloseq github 
https://github.com/joey711/phyloseq/issues/956

It seems that there are some differences in calculation between qiime2 and phyloseq. Have anyone tested this? Is it possible to check if it is also the case with tse?

**Comment by antagomir** [comment]
Thanks, this is important.

The conclusion seem to be that _rbiom_ matches best with QIIME2 (and gives similar results to 2 other independent R implementations as well but not with _phyloseq_). It is also the fastest R implementation.

-> mia should be updated to use _rbiom_ implementation!

**Comment by antagomir** [comment]
any volunteers for a quick PR..?

**Comment by antagomir** [comment]
Also see FuncDiv that implemented this same suggestion in [issue 2](https://github.com/gavinmdouglas/FuncDiv/issues/2#event-8666748512).

**Comment by antagomir** [comment]
Link with issue #340

**Comment by ndegunst** [comment]
The calculateUnifrac file seems to implement it's own version of unifrac inspired from the phyloseq function without actually using other packages : [calculate_Unifrac.R](https://github.com/microbiome/mia/blob/devel/R/calculateUnifrac.R).

I've been trying to find the difference between the phyloseq implementation and the rbiom implementation to no avail. 
The Rbiom version uses a function coded in c++ which i have a hard time understanding given my limited knowledge on both c++ and unifrac.

**Comment by antagomir** [comment]
The idea would be to use this as a dependency, and just call the _rbiom_ function (internally from mia), instead of the current solution which is to call phyloseq internally -> you wouldn't need to know how rbiom works internally if you can replace the phyloseq unifrac call with the rbiom unifrac call.

**Comment by TuomasBorman** [comment]
@thpralas has checked this unifrac thing little bit

**Comment by antagomir** [comment]
Ok - then let @thpralas take care

**Comment by antagomir** [comment]
It was not assigned to anyone, so I had passed it on. Let's aim to use the assignments on the top right to indicate if someone works on something, this way we can avoid overlaps.

**Comment by TuomasBorman** [comment]
Yes, that's ok. As we have now more contributors, it is better to switch using the "assignees" field.

**Comment by theotimeee** [comment]
I have not checked the rbiom implementation of unifrac yet but I looked at the picante implementation (`picante::unifrac`).
My initial goal was to replace mia `runUnifrac` function by calling `picante::unifrac` internally in `calculateUnifrac`. 

The picante implementation takes as parameters a community matrix and a tree. I think that the aggregation of the matrix based on `nodeLab` should be done in `calculateUnifrac` function (instead of doing it in the `runUnifrac` function) because it is necessary to aggregate the matrix even though we use `picante::unifrac`.
However, with @TuomasBorman help, I realized while debugging `calculateUnifrac` and `picante::unifrac` that `picante::unifrac` may be too slow for big TreeSummarizedExperiment (e.g. GlobalPatterns), and I did not manage to get a result.
The picante package does not have a fast implementation of unifrac so I do not think we could use it internally to replace `runUnifrac`.
I am going to look at the rbiom implementation of unifrac.

**Comment by TuomasBorman** [comment]
Little bit related to this same thing: also faith index implementation could be changed so that we use external package instead of our own implementation.

Good thing about picante was that it included also faith alpha diversity index, rbiom seems not to include it.

**Comment by antagomir** [comment]
Note the original discussion above. It included both _picante_ and _rbiom_, and the latter seemed better overall: "The conclusion seem to be that rbiom matches best with QIIME2 (and gives similar results to 2 other independent R implementations as well but not with phyloseq). It is also the fastest R implementation."

**Comment by antagomir** [comment]
I opened a distinct issue on Faith in #522

**Comment by antagomir** [comment]
My primary preference is _rbiom_ for the above mentioned reason

**Comment by antagomir** [comment]
@thpralas is this issue ready & could be closed?

**Comment by theotimeee** [comment]
> @thpralas is this issue ready & could be closed?

Yes I think this issue is now ready and can be closed since mia unifrac implementation now internally calls rbiom instead of phyloseq (https://github.com/microbiome/mia/pull/523)
