### ISSUE TITLE
Create a wrapper for the clusterRows method

### ISSUE THREAD

**Issue by Basil-Courbayre-Dussau** [microbiome/mia#363]
The idea is to have a wrapper for bluster, especially the `clusterRows` function to facilitate its use in `mia`.
For now, clustering using bluster can be done this way
```R
data("GlobalPatterns", package = "mia")
tse <- GlobalPatterns
tse <- transformCounts(tse, method = "relabundance")
x <- t(assay(tse, "relabundance"))
hclust.out <- clusterRows(x, HclustParam())
colData(tse)$clusters <- hclust.out
```

With the wrapper, the code would look like this:
```R
data("GlobalPatterns", package = "mia")
tse <- GlobalPatterns
tse <- transformCounts(tse, method = "relabundance")

#Either this way with separate methods to cluster on the rows/cols
tse <- clusterRows(tse, "relabundance", HclustParam())

# Or this way with one unique method to cluster with an additional parameter
tse <- cluster(tse, "relabundance", transpose=T, HclustParam())
```
This wrapper would simply take the chosen assay, transpose it if necessary, call the `clusterRows` method and update the `tse` object by adding a `colData` or a `rowData`.

This wrapper could be useful to have a function that resembles the others in the package (in that it has the parameters for the `SummarizedExperiment` object and the assay: `assay_name`). It would allow to call the plotting functions immediately once the `clusterRows` method has been called.

As far as plotting goes, I believe it would stay the same:
```R
tse <- runMDS(tse, assay.type = "relabundance", FUN = vegan::vegdist, method = "bray")

plotReducedDim(tse, "MDS", colour_by = "clusters")
```

One remaining question is how the wrapper would work if we want the full information from the clustering: for example when calling clusterRows with the parameter `full= TRUE`.

This would give information about the clustering that can be later used (to plot the dendrogram for example) but it needs to be stored somewhere. I see two solutions here but there might be more.
* We can store the information in the metadata of the TSE which would be simple to use but this might not be the kind of content that is expected to be in the metadata. In addition, we could create functions to retrieve that information. For example:
```R
result <- cluster(tse, "relabundance", transpose=T, HclustParam(), full= TRUE)
tse <- result$tse
hclust.out <- metadata(tse)[["hclust"]]
```
* Or we could return an object containing the tse and the additional data. But that wouldn't be very handy. For example:
```R
result <- cluster(tse, "relabundance", transpose=T, HclustParam(), full= TRUE)
tse <- result$tse
hclust.out <- result$data
```

What do you think of this?

**Comment by TuomasBorman** [comment]
Nice!

1. I think `cluster` method could be useful. 
2. I think `MARGIN `is better than `transpose` parameter since that is more explicit (See `getExperimentCrossAssociation` for instance)
3. metadata is right place to store the full clustering results (and row/colData)

**Comment by Basil-Courbayre-Dussau** [comment]
I see, thanks! 
Should I start working on this? Or are there things we should discuss further (such as other functionalities you'd like to see in that file/function)?

**Comment by antagomir** [comment]
Thanks! Remarks:

1. `assay_name` is `assay.type` in the latest versions at least in mia, scuttle and scran. Not sure about bluster. To be checked, it should be synchronized.

2. I like the idea of a single method `cluster`, and agree about `MARGIN`. However, I know that rows and columns typically need their own clustering methods (samples are clustered with ecological dissimilarities; taxa are clustered with co-abundance measure that are often also compositionally aware). However, perhaps we can have separate methods for determining frequently used special cases of row or col clusterings. There might be space for one very generic clustering method that doesn't care about row/col distinction.

3. I agree about storing stuff in row / colData where feasible, and rest in metadata

4. The `cluster` command should either return a (Tree)SE object or something that can be readily used for analysis or inserted into SE object (cf. `runMDS` vs. `calculateMDS` in _scater_ package). Input and output types should match in the former case (like SE->SE, TreeSE -> TreeSE, SCE -> SCE...)

5. Could be implemented in mia, or in bluster (if accepted). Probably easier to first prepare in mia, then consider this when it works.

I like the idea of collapsing the procedure from 3 lines to 1 line but also interested to check first why  `clusterRows` was originally implemented for numeric matrices rather than SCE objects. Let's come back to this in a bit.

**Comment by antagomir** [comment]
Yes - the situation is complicated by the fact that clustering can operate on assays, altExps, reducedDims etc etc. The user needs to specify many details in order to do this.

**Comment by TuomasBorman** [comment]
General cluster function: This is similar to transformSamples/Features. We decided to have only transformCounts

I guess this clustering is done mostly on assays (altExp option can also be easily included). This method could still have an additional value as it 1) makes things little bit easier 2) stores the data to the object 3) enables a direct usage with TreeSE object

**Comment by antagomir** [comment]
It feels that it could be worth trying out and having some more of these generic functions.
