### ISSUE TITLE
Absolute vs. relative abundances

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#4]
Some microbiome studies are starting to report measures of absolute abundance in addition to sequencing read counts and relative abundances. The `MicrobiomeExperiment` could/should support incorporating this information, too.

**Comment by FelixErnst** [comment]
See FelixErnst/MicrobiomeExperiment#19 for getter/setter added

**Comment by adw96** [comment]
Just a really quick plug advocating against the idea of rescaling relative abundances (obtained from shotgun or amplicon) by absolute abundances. The reasons for the strong no are here (https://elifesciences.org/articles/46923) and an alternative is here (https://www.biorxiv.org/content/10.1101/761486v1).

**Comment by antagomir** [comment]
Great, thanks @adw96 - my intention was mainly to prepare for future developments in measurement technologies (as this class may be potentially long-living), rather than use this for the currently available measurement techniques. Fully agree with the challenges.

**Comment by FelixErnst** [comment]
@adw96 wouldn't the addition of this type of sample data allow the variable efficiency estimate to be computed based on the appropriate count matrix?

It would probably quite straight forward to write an interface for paramedic, if my assumption is correct.

edit: OK I see, that the sample concentration `paramedic` needs is also two dimensional. So that doesn't work out of the box with these changes.
