### ISSUE TITLE
Conversion function from TSE to phyloseq

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#42]
This would be pretty useful to have since we can then make TSE the default format, and convert to phyloseq only when corresponding functionality is only available for phyloseq.

**Comment by antagomir** [comment]
Name for that function would be `makephyloseqFromTreeSummarizedExperiment` if we follow the current package conventions (we already have `makeTreeSummarizedExperimentFromphyloseq`).

However I started to think whether `convertTreeSummarizedExperimentTophyloseq` or `TSE2phyloseq` would be better? These are essentially conversions and no need to emphasize the "make" part. Same comment goes for the other similar names.

**Comment by FelixErnst** [comment]
I don't like the `TSE2phyloseq` name, because it does not contain a verb.

Having said that, then this is just about `make` vs. `convert`. If I look at the Bioconductor verse, the `make` verb is much preferred. `makeSummarizedExperimentFromDataFrame`, `makeSummarizedExperimentFromLoom`, `makeTxDbFromBiomart` and `makeGRangesListFromDataFrame` are just a few examples from my current session, whereas for the `convert` verb I couldn't find anything.

So from this brief investigation, I would conclude the `make` verb is preferred and also would go so far as to say that the `make` verb is expected.

**Comment by antagomir** [comment]
That's ok. Then there is the related broader issue #45
