### ISSUE TITLE
associate

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#65]
The microbiome pkg has function [associate](https://github.com/microbiome/microbiome/blob/master/R/associate.R) to cross-correlate (or associate) taxonomic and other features for instance for [heatmap visualizations](https://microbiome.github.io/tutorials/Heatmap.html) of such associations. 

We could discuss whether such functionality is needed in `mia` (either based on the microbiome::associate, or entirely redesigned based on some other external packages). There are many different techniques in the R universe for such tasks but in the context of `SE` data, which is specifically suited for multi-omics / multi-source analyses, an easy access to a standard set of such associative techniques could be justified and facilitate exploration & visualization.

**Comment by FelixErnst** [comment]
I think this a broad topic, which is probably best moved to `MiaBook`. The examples from `microbiome` show a clear example, but this cannot be generalized in a sense, that it works for all datasets independent of size, at least for the plotting functions. At some point they become just to big to make sense of.
 In addition, tools like `MOFA2` provided probably a more comprehensive way of investigation multi-omics datasets right know. `mia` with is specific focus on microbiome work, is probably to specific for it to make sense in the long run.

**Comment by antagomir** [comment]
Yes I agree completely. It could make more sense to provide example workflows for this kind of things, rather than specific functions.

**Comment by antagomir** [comment]
I now opened this as an [issue#16](https://github.com/microbiome/MiaBook/issues/16) in MiaBook.

**Comment by antagomir** [comment]
I would like to revisit this discussion.

Simple non-parametric Spearman correlations, or other related measures, would work regardless of the assay and data size considerations, for exploratory purposes, as long as the user has any idea what they are doing. This is common routine operation that then often needs to be complemented with more dedicated anayses with other techniques.

I still suggest to provide association function in mia to assess cross-associations between two assays; a suitable name could be e.g. `calculateAssayDependencies`. This can then be complemented with a complementary heatmap visualization `plotAssayDependencies`.

Related to (longish) examples in [OMA PR#73](https://github.com/microbiome/OMA/pull/73)

**Comment by FelixErnst** [comment]
The problem I have with this is the layer of abstraction.

`calculateAssayDependencies` is a very high level name and it is not clear what this function would or should do:
1. dependencies suggest a 1:1 relation. Either something depends or it does not and it depends a bit is actually better said with "associated".
2. Second the association of assays is very well defined. It is a 1:1 relation for the feature and the samples, because otherwise you cannot put two assays in one SE

From this I can gather that your are actually thinking of using a `MultiAssayExperiment` object as input as suggested by https://microbiome.github.io/tutorials/Heatmap.html

Is that correct?

If so, I would venture the guess, that we are not the first to wonder how features of two experiments are associated, which means the likelyhood that there is already function out there doing something similar is high. I would start checking for packages which have the `MultiAssayExperiment` package as a dependency: https://bioconductor.org/packages/release/bioc/html/MultiAssayExperiment.html

If that doesn't yield a good result, maybe a function called `getExperimentAssociation` or `getExperimentCrossCorrelation` can be implemented. However, this would blow the dependency tree of `mia` up even further. I don't have a solution for that right now, but lets see what functions are already available.

**Comment by antagomir** [comment]
Yes, I agree with all points, and exploring first more thoroughly the available "function space".. 

Association is more generic than CrossCorrelation and may be therefore necessary.

**Comment by FelixErnst** [comment]
Can this be closed? Whats the current summarized view on this?

**Comment by TuomasBorman** [comment]
I tried to find methods for cross-correlation that have `MultiAssayExperiment` as dependency, but couldn't find one. I think this would be nice to have

**Comment by FelixErnst** [comment]
So a PR is/might be incoming? Can you link it with this issue, when the time comes?

**Comment by TuomasBorman** [comment]
Yes, I can make that, I will link it with this issue
